### ISSUE TITLE
localでsupabaseへのアクセス制限があるみたい？

### ISSUE THREAD

**Issue by wshi8912** [wshi8912/diagrammingai#49]
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _handleRequest (/home/user/work/diagrammingai/node_modules/@supabase/gotrue-js/dist/main/lib/fetch.js:64:18)
    at async _request (/home/user/work/diagrammingai/node_modules/@supabase/gotrue-js/dist/main/lib/fetch.js:56:18)
    at async /home/user/work/diagrammingai/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:781:24
    at async SupabaseAuthClient._useSession (/home/user/work/diagrammingai/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:698:20)
    at async SupabaseAuthClient._getUser (/home/user/work/diagrammingai/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:775:20)
    at async /home/user/work/diagrammingai/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:763:20
    at async /home/user/work/diagrammingai/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:643:28 {
  cause: Error: certificate is not yet valid

**Comment by wshi8912** [comment]
WSLのクロック修正コマンドで対応
